services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.consulcatalog=true"
      - "--providers.consulcatalog.prefix=traefik"
      - "--providers.consulcatalog.endpoint.address=consul:8500"
      - "--serversTransport.insecureSkipVerify=true"
      - "--entryPoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    labels:
      - "traefik.enable=true"
      - "traefik.consulcatalog.connect=true"
    command: agent -server -bootstrap -ui -client=0.0.0.0
    ports:
      - "8500:8500"

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: record
    ports:
      - "3306:3306"

  record:
    build: ./services/record
    container_name: record
    # change in the future when we actually implement traefik and consul
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "3000:3000"
